### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AkhilKallepalli** [brandawg/Cranfield_Thesis_Template#1]
- Add documentation of correction of quotation marks from ``__" to ""__""
- Italicise or Remove the "1." in the page headers of Introduction Chapter (for example)
   To be displayed as **_Introduction_**
- Correct page numbers to roman numerals or "i, ii, iii, ...." prior to Chapter 1. 

TIA

**Comment by brandawg** [comment]
- [x] Add documentation of correction of quotation marks from ``" to """"
- [x] Italicise or Remove the "1." in the page headers of Introduction Chapter (for example). To be displayed as *_Introduction_*
- [x] Correct page numbers to roman numerals or "i, ii, iii, ...." prior to Chapter 1.

**Comment by brandawg** [comment]
- As discussed Header clarity has been improved. 
- Page numbering has to be explicitly defined in the document. This has been highlighted in the updated example file.
- Use `\pagenumbering{Roman}` and `\pagenumbering{arabic}` as desired. Be aware when you use these commands as shown they will reset your page count to 1.
